package model

import "fmt"

func DescribeRecord1(r Record) string   { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord2(r Record) string   { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord3(r Record) string   { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord4(r Record) string   { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord5(r Record) string   { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord6(r Record) string   { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord7(r Record) string   { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord8(r Record) string   { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord9(r Record) string   { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord10(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord11(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord12(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord13(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord14(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord15(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord16(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord17(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord18(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord19(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord20(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord21(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord22(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord23(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord24(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord25(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord26(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord27(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord28(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord29(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord30(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord31(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord32(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord33(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord34(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord35(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord36(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord37(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord38(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord39(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord40(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord41(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord42(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord43(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord44(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord45(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord46(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord47(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord48(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord49(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord50(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord51(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord52(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord53(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord54(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord55(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord56(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord57(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord58(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord59(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord60(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord61(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord62(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord63(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord64(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord65(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord66(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord67(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord68(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord69(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord70(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord71(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord72(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord73(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord74(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord75(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord76(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord77(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord78(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord79(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord80(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord81(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord82(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord83(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord84(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord85(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord86(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord87(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord88(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord89(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord90(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord91(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord92(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord93(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord94(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord95(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord96(r Record) string  { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord97(r Record) string  { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord98(r Record) string  { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord99(r Record) string  { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord100(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord101(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord102(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord103(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord104(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord105(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord106(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord107(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord108(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord109(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord110(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord111(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord112(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord113(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord114(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord115(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord116(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord117(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord118(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord119(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord120(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord121(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord122(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord123(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord124(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord125(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord126(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord127(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord128(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord129(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord130(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord131(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord132(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord133(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord134(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord135(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord136(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord137(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord138(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord139(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord140(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord141(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord142(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord143(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord144(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord145(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord146(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord147(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord148(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord149(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord150(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord151(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord152(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord153(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord154(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord155(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord156(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord157(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord158(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord159(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord160(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord161(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord162(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord163(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord164(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord165(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord166(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord167(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord168(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord169(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord170(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord171(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord172(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord173(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord174(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord175(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord176(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord177(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord178(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord179(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord180(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord181(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord182(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord183(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord184(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord185(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord186(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord187(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord188(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord189(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord190(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord191(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord192(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord193(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord194(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord195(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord196(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord197(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord198(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord199(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord200(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord201(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord202(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord203(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord204(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord205(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord206(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord207(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord208(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord209(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord210(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord211(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord212(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord213(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord214(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord215(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord216(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord217(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord218(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord219(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord220(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord221(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord222(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord223(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord224(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord225(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord226(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord227(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord228(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord229(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord230(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord231(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord232(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord233(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord234(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord235(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord236(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
func DescribeRecord237(r Record) string { return fmt.Sprintf("%s:%s:0", r.ID, r.Status) }
func DescribeRecord238(r Record) string { return fmt.Sprintf("%s:%s:1", r.ID, r.Status) }
func DescribeRecord239(r Record) string { return fmt.Sprintf("%s:%s:2", r.ID, r.Status) }
func DescribeRecord240(r Record) string { return fmt.Sprintf("%s:%s:3", r.ID, r.Status) }
