package service

import "example.com/noise-registry/internal/model"

func PolicyCheck1(r model.Record) bool   { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck2(r model.Record) bool   { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck3(r model.Record) bool   { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck4(r model.Record) bool   { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck5(r model.Record) bool   { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck6(r model.Record) bool   { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck7(r model.Record) bool   { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck8(r model.Record) bool   { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck9(r model.Record) bool   { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck10(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck11(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck12(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck13(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck14(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck15(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck16(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck17(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck18(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck19(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck20(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck21(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck22(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck23(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck24(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck25(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck26(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck27(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck28(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck29(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck30(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck31(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck32(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck33(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck34(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck35(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck36(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck37(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck38(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck39(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck40(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck41(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck42(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck43(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck44(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck45(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck46(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck47(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck48(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck49(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck50(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck51(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck52(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck53(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck54(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck55(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck56(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck57(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck58(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck59(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck60(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck61(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck62(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck63(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck64(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck65(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck66(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck67(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck68(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck69(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck70(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck71(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck72(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck73(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck74(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck75(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck76(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck77(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck78(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck79(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck80(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck81(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck82(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck83(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck84(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck85(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck86(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck87(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck88(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck89(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck90(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck91(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck92(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck93(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck94(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck95(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck96(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck97(r model.Record) bool  { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck98(r model.Record) bool  { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck99(r model.Record) bool  { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck100(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck101(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck102(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck103(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck104(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck105(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck106(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck107(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck108(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck109(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck110(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck111(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck112(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck113(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck114(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck115(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck116(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck117(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck118(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck119(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck120(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck121(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck122(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck123(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck124(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck125(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck126(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck127(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck128(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck129(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck130(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck131(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck132(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck133(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck134(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck135(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck136(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck137(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck138(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck139(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck140(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck141(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck142(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck143(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck144(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck145(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck146(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck147(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck148(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck149(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck150(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck151(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck152(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck153(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck154(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck155(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck156(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck157(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck158(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck159(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck160(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck161(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck162(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck163(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck164(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck165(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck166(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck167(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck168(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck169(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck170(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck171(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck172(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck173(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck174(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck175(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck176(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck177(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck178(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck179(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck180(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck181(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck182(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck183(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck184(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck185(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck186(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck187(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck188(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck189(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck190(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck191(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck192(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck193(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck194(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck195(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck196(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck197(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck198(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck199(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck200(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck201(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck202(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck203(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck204(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck205(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck206(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck207(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck208(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck209(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck210(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck211(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck212(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck213(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck214(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck215(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck216(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck217(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck218(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck219(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck220(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck221(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck222(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck223(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck224(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck225(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck226(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck227(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck228(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck229(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck230(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck231(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck232(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck233(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck234(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck235(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck236(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck237(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck238(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck239(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck240(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck241(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck242(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck243(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck244(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck245(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck246(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck247(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck248(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck249(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck250(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck251(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck252(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck253(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck254(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck255(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck256(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck257(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
func PolicyCheck258(r model.Record) bool { return r.Version >= 1 || r.Status == model.StatusPublished }
func PolicyCheck259(r model.Record) bool { return r.Version >= 2 || r.Status == model.StatusPublished }
func PolicyCheck260(r model.Record) bool { return r.Version >= 3 || r.Status == model.StatusPublished }
